#重置（清空）k8s集群
#--------------------------------------------------------------------
- hosts: etcd
  tasks:
  - name: 删除容器
    tags: reset,reset-etcd
    shell: "docker rm -vf etcd"
    ignore_errors: yes
  - name: 删除目录
    tags: reset,reset-etcd
    file:
      path: "{{ item }}"
      state: absent
    with_items:
    - /etc/kubernetes
    - /tmp/etcd
    - /var/lib/etcd
- hosts: node,master
  tasks:
  - name: 重置K8s
    tags: reset,reset-k8s
    shell: kubeadm reset -f
  - name: 重置iptables
    tags: reset,reset-k8s
    shell: iptables -F && iptables -t nat -F && iptables -t mangle -F && iptables -X
  - name: 删除cni0网桥
    tags: reset,reset-k8s
    shell: ip link del cni0
    ignore_errors: yes
  - name: 删除flannel.1网桥
    tags: reset,reset-k8s
    shell: ip link del flannel.1
    ignore_errors: yes
  - name: 重启docker
    tags: reset,restart-docker
    shell: systemctl restart docker
  - name: 重启kubelet
    tags: reset,restart-kubelet
    shell: systemctl restart kubelet